SELECT
  YEAR(O.SALES_DATE) AS YEAR,
  MONTH(O.SALES_DATE) AS MONTH,
  COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
  ROUND(COUNT(DISTINCT O.USER_ID) / U.ALL_USERS, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE O
JOIN USER_INFO I
  ON I.USER_ID = O.USER_ID
JOIN (
  SELECT COUNT(*) AS ALL_USERS
  FROM USER_INFO
  WHERE JOINED >= '2021-01-01' AND JOINED < '2022-01-01'
) U
WHERE I.JOINED >= '2021-01-01' AND I.JOINED < '2022-01-01'
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR, MONTH;
